### ISSUE TITLE
Read & Display CANBUS

### ISSUE THREAD

**Issue by LDwhoRU** [QUT-Motorsport/QUTMS_SteeringWheel_V2#1]

**Comment by cwljohnson** [comment]
[Steering-wheel-button-and-menu-design.docx](https://github.com/QUT-Motorsport/QUTMS_SteeringWheel_V2/files/4052015/Steering-wheel-button-and-menu-design.docx)

Original spec for the steering wheel, not sure if this is still current etc

**Comment by cwljohnson** [comment]
Current status: existing CANbus chip is shorting out or something. Matt has acquired new CANbus chips for it (currently located near soldering station in the lab, next to the steering wheel board), so need to ask him, Josh, or Liam (or any electrical bros) to swap the chips out.

This chip might be different model to one already on steering wheel, so code regarding CANbus may need to be altered/rewritten for the steering wheel.

Once those two things are done, should have no issues with plugging it back into the car and trying to read CANbus messages from the chassis controller.

Also finally, regarding chassis controller, maybe best to unplug logger while testing this, in case logger (which reads all canbus messages it can find), is consuming all the messages before steering whele can read it (which could lead into a potential redo of the CANbus libraries if this occurs, not sure best to find out if this does happen and if so i'll look into it)

**Comment by cwljohnson** [comment]
New CAN chip is a MCP2561, whereas existing is MCP2517, so code MIGHT work but probably best to go thru the datasheet and check its doing everything correctly.

[MCP2517 Datasheet](http://ww1.microchip.com/downloads/en/DeviceDoc/MCP2517FD-External-CAN-FD-Controller-with-SPI-Interface-20005688B.pdf) (previous chip)

[MCP2561 Datasheet](http://ww1.microchip.com/downloads/en/DeviceDoc/20005167C.pdf) (new chip)

**Comment by cwljohnson** [comment]
We're redesigning Steering Wheel software wise, and after that this should be working fine, can bring it up again if need be.
